# Generated by Django 4.1.2 on 2022-11-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photanic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
